# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Johnny's Blog
author: #Johnny
email: #your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Programming, data science, applied math, etc.

avatar: https://github.com/Johnns620/Johnns620.github.io/images/KONG.JPG



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Johnns620.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  JohnSell620
linkedin_username: johnny-sellers-b26819128
# stackoverflow_username: users/4518224/johnny-sellers
twitter:
  username: JohnnySellers62
  card: summary
  
google_analytics: UA-120544244-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
